PORT = 8888
ACTIONS_PATH = r"/leds"
DISCOVERY_PATH = r"/discovery"
SERVER_IP = "192.168.1.106"

ACTIONS_REMOTE_URL = f"ws://{SERVER_IP}{ACTIONS_PATH}:{PORT}"
ACTIONS_DISCOVERY_URL = f"http://{SERVER_IP}{DISCOVERY_PATH}:{PORT}"